version: 2

models:
  - name: mart_regulator_kpis_monthly
    columns:
      - name: report_period
        tests:
          - not_null
      - name: operator_id
        tests:
          - not_null
      - name: service_segment
        tests:
          - not_null
          - accepted_values:
              values: ['mobile', 'fixed_voice', 'fixed_broadband']
      - name: total_revenue_xaf
        tests:
          - not_null

  - name: mart_quality_events_open
    columns:
      - name: report_period
        tests:
          - not_null
      - name: severity
        tests:
          - accepted_values:
              values: ['info', 'warning', 'error', 'critical']
      - name: open_event_count
        tests:
          - not_null
